#!/bin/bash
# VIM Control Script

VIM=gvim # vim|gvim|nvim etc...

echo "Open in:"

existing_server_list=(`$VIM --serverlist`)

if ((${#existing_server_list[@]} != 0)); then
	let 'i = 1'
	for server in ${existing_server_list[@]}; do
		echo -e "\t[$i] $server"
		let 'i += 1'
	done
fi

echo -e "\t[<name>] New $VIM instance with <name>"
echo -e "\t[<enter>] New $VIM instance with default name"

read user_command

if [ -z "$user_command" ]; then
	exec $VIM "$@"
fi

if [[ $date =~ [^0-9a-Z_-]+ ]]; then
	echo "Invalid symbols used"
	exit -1
fi

if ((user_command >= 1 && user_command <= ${#existing_server_list[*]})); then
	let 'index = user_command - 1'
	server=${existing_server_list[$index]}
else
	server="$user_command"
fi

# Convert to upper case
server=${server^^}

if [ $# != 0 ]; then
	exec $VIM --servername $server --remote-silent "$@"
else
	# Get currently active buffer name
	bufname=`$VIM --servername $server --remote-expr 'bufname("")' 2> /dev/null`
	if [ -z "$bufname" ]; then
		echo "No new buffers open in $VIM. Impossible to focus."
	else
		$VIM --servername $server --remote-silent "$bufname"
	fi

fi
